

package GUI;

import DATA.UserData;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 *GUI for login dialog
 * @author Yu Liu
 */
public class LoginDialog extends javax.swing.JDialog {
    
    
    public static final int RET_CANCEL = 0;
    
    public static final int RET_OK = 1;

    /**
     * Creates new form RegisterDialog
     * @param parent 
     * @param modal 
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        WindowUtil.center(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(4, 0));
        jPanel1.add(jPanel3);

        jLabel1.setText("UserName:");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel4.add(jLabel1);

        fieldUserName.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel4.add(fieldUserName);

        jPanel1.add(jPanel4);

        jLabel2.setText("Password:");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel5.add(jLabel2);

        fieldPassword.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel5.add(fieldPassword);

        jPanel1.add(jPanel5);
        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 60));

        buttonOk.setText("Ok");
        buttonOk.setHideActionText(true);
        buttonOk.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        jPanel2.add(buttonOk);

        buttonCancel.setText("Cancel");
        buttonCancel.setHideActionText(true);
        buttonCancel.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);
        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        returnStatus=RET_CANCEL;
        setVisible(false);
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        UserData userDao=UserData.getInstance();
        String userName=fieldUserName.getText().trim();
        // user name can not be empty
        if(userName.length()==0){
            JOptionPane.showMessageDialog(this, "please input user name");
            return;
        }
        String password=new String(fieldPassword.getPassword());
        // password can not be empty
        if(password.length()==0){
            JOptionPane.showMessageDialog(this, "please input password");
            return;
        }
        User user=userDao.getUser(userName);
        // check the username and password 
        if(user==null||!user.getPassword().equalsIgnoreCase(password)){
            JOptionPane.showMessageDialog(this, "Login failed.");
            return;            
        }
        userDao.setLoginUser(user);
        returnStatus=RET_OK;
        setVisible(false);
    }//GEN-LAST:event_buttonOkActionPerformed

    public int getReturnStatus() {
        return returnStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
