
package GUI;

import DATA.QuestionData;
import DATA.UserData;
import Model.Question;
import Model.User;
import javax.swing.JOptionPane;

/**
 * GUI for mind competition
 * @author Yu Liu
 */
public class MindCompetition extends javax.swing.JDialog {

    private UserData userData;
    private QuestionData questionData;
    private User user;
    private Question question;
    /**
     * Creates new form MindCompetition
     * @param parent 
     * @param modal 
     */
    public MindCompetition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        userData=UserData.getInstance();
        user=userData.getLoginUser();
        questionData=QuestionData.getInstance();
        nextQuestion();
        user.setStatus("Study");
        WindowUtil.center(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaQuestion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldAnswer = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Study");
        setPreferredSize(new java.awt.Dimension(900, 360));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Question"));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        textAreaQuestion.setEditable(false);
        textAreaQuestion.setColumns(20);
        textAreaQuestion.setRows(5);
        textAreaQuestion.setName(""); // NOI18N
        textAreaQuestion.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(textAreaQuestion);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer"));
        jPanel2.setToolTipText("");

        jLabel1.setText("Please input answer :");
        jPanel2.add(jLabel1);

        fieldAnswer.setPreferredSize(new java.awt.Dimension(160, 21));
        jPanel2.add(fieldAnswer);

        buttonSubmit.setText("Submit");
        buttonSubmit.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSubmit);

        buttonNext.setText("Next");
        buttonNext.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });
        jPanel2.add(buttonNext);

        jButton1.setText("Exit");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextQuestion(){
        question=questionData.nextQuestion();
        textAreaQuestion.setText(question.getSubject());
        textAreaQuestion.setText(question.getSubject());
        fieldAnswer.setText("");
        fieldAnswer.requestFocus();
    }
    
    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        String answer=fieldAnswer.getText().trim();
        // the answer can not be empty
        if(answer.length()==0){
            JOptionPane.showMessageDialog(this, "please input answer");
            return;
        }
        // check the answer is right or wrong
        if(answer.equalsIgnoreCase(question.getCorrect())){
            userData.addMoney(user, 10);
            JOptionPane.showMessageDialog(this, "correct money +10");
        }else{
            JOptionPane.showMessageDialog(this, "wrong answer");            
        }
        nextQuestion();
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        nextQuestion();
    }//GEN-LAST:event_buttonNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JTextField fieldAnswer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaQuestion;
    // End of variables declaration//GEN-END:variables
}
