
package GUI;

import DATA.UserData;
import Model.User;
import java.awt.Window;
import javax.swing.JOptionPane;

/**
 *
 * the GUI for select register
 * 
 * @author Yu Liu
 */
public class RegisterDialog extends javax.swing.JDialog {
    
    public static final int RET_CANCEL = 0;
    
    public static final int RET_OK = 1;

    /**
     * Creates new form RegisterDialog
     * @param parent
     * @param modal  
     */
    public RegisterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        WindowUtil.center(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldPetName = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        radioButton1 = new javax.swing.JRadioButton();
        radioButton2 = new javax.swing.JRadioButton();
        radioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register User");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));
        jPanel1.add(jPanel3);

        jLabel1.setText("UserName:");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel4.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        fieldUserName.setPreferredSize(new java.awt.Dimension(120, 21));
        jPanel4.add(fieldUserName);

        jPanel1.add(jPanel4);

        jLabel2.setText("Password:");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel5.add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        fieldPassword.setPreferredSize(new java.awt.Dimension(120, 21));
        jPanel5.add(fieldPassword);

        jPanel1.add(jPanel5);

        jLabel3.setText("Pet Name:");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 15));
        jPanel6.add(jLabel3);
        jLabel3.getAccessibleContext().setAccessibleDescription("");

        fieldPetName.setPreferredSize(new java.awt.Dimension(120, 21));
        jPanel6.add(fieldPetName);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/sdog1.jpg"))); // NOI18N
        jPanel7.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/sdog2.jpg"))); // NOI18N
        jPanel7.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/sdog3.jpg"))); // NOI18N
        jPanel7.add(jLabel6);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroup1.add(radioButton1);
        radioButton1.setSelected(true);
        radioButton1.setText("doge");
        radioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(radioButton1);

        buttonGroup1.add(radioButton2);
        radioButton2.setText("space dog");
        radioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(radioButton2);

        buttonGroup1.add(radioButton3);
        radioButton3.setText("cute");
        radioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(radioButton3);

        jPanel8.add(jPanel9);

        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 60));

        buttonOk.setText("Ok");
        buttonOk.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        jPanel2.add(buttonOk);

        buttonCancel.setText("Cancel");
        buttonCancel.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancel);

        jPanel8.add(jPanel2);

        getContentPane().add(jPanel8, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        returnStatus=RET_CANCEL;
        setVisible(false);
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        UserData userDao=UserData.getInstance();
        String userName=fieldUserName.getText().trim();
        // user name can not be empty
        if(userName.length()==0){
            JOptionPane.showMessageDialog(this, "please input user name");
            return;
        }
        // user name exised
        if(userDao.getUser(userName)!=null){
            JOptionPane.showMessageDialog(this, "User Name Exist.");
            return;            
        }
        String password=new String(fieldPassword.getPassword());
        // password can not be empty
        if(password.length()==0){
            JOptionPane.showMessageDialog(this, "please input password");
            return;
        }
        String petName=fieldPetName.getText().trim();
        if(petName.length()==0){
            petName=userName;
        }
        String kind;
        if(radioButton1.isSelected()){
            kind="dog1";
        }else if(radioButton2.isSelected()){
            kind="dog2";
        }else{
            kind="dog3";
        }
        User newUser = userDao.addUser(userName, password, petName,kind);
        userDao.setLoginUser(newUser);
        returnStatus=RET_OK;
        setVisible(false);
    }//GEN-LAST:event_buttonOkActionPerformed

   
    public int getReturnStatus() {
        return returnStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton radioButton1;
    private javax.swing.JRadioButton radioButton2;
    private javax.swing.JRadioButton radioButton3;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
