
package GUI;

import DATA.ItemsData;
import DATA.UserData;
import Model.Item;
import Model.Pet;
import Model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * the GUI for shop dialog
 * 
 * @author Yu Liu
 */
public class ShopDialog extends javax.swing.JDialog {

    /**
     * Creates new form ShopDialog
     * @param parent
     * @param modal  
     */
    public ShopDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UserData.getInstance().getLoginUser().setStatus("Shop");
        WindowUtil.center(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGoods = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonBuy = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shop");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Goods"));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tableGoods.setModel(new GoodsTableModel());
        tableGoods.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableGoods);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setToolTipText("");

        buttonBuy.setText("Buy");
        buttonBuy.setFocusPainted(false);
        buttonBuy.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuyActionPerformed(evt);
            }
        });
        jPanel2.add(buttonBuy);

        jButton1.setText("Exit");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuyActionPerformed
        ItemsData goodsDao=ItemsData.getInstance();
        UserData userDao=UserData.getInstance();
        int index=tableGoods.getSelectedRow();
        if(index>=0){
            Item goods=goodsDao.get(index);
            User user=userDao.getLoginUser();
            Pet pet=user.getPet();
            //check the user has enough money or not
            if(pet.getMoney()<goods.getPrice()){
                JOptionPane.showMessageDialog(this, "money is not enough!");
            }else{
                userDao.buy(userDao.getLoginUser(), goods);
                JOptionPane.showMessageDialog(this, "purchase success!");

            }
        }
    }//GEN-LAST:event_buttonBuyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuy;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGoods;
    // End of variables declaration//GEN-END:variables

    // this method creat the new items table model
    private class GoodsTableModel extends DefaultTableModel {

        // get the count of column
        @Override
        public int getColumnCount() {
            return 6;
        }

        // get the count of row
        @Override
        public int getRowCount() {
            ItemsData goodsDao = ItemsData.getInstance();
            return goodsDao.count();
        }

        // get the title of every row
        @Override
        public String getColumnName(int column) {
            switch(column){
                case 0:
                    return "Name";
                case 1:
                    return "Price";
                case 2:
                    return "strength";
                case 3:
                    return "agility";
                case 4:
                    return "stamina";
                case 5:
                    return "happiness";
            }
            return "";
        }

        // show the item detials in table
        @Override
        public Object getValueAt(int row, int column) {
            ItemsData goodsDao = ItemsData.getInstance();
            Item goods=goodsDao.get(row);
            switch(column){
                case 0:
                    return goods.getName();
                case 1:
                    return goods.getPrice();
                case 2:
                    return goods.getStrength();
                case 3:
                    return goods.getAgility();
                case 4:
                    return goods.getStamina();
                case 5:
                    return goods.getHappiness();
            }
            return "";
        }

    }
}
