
package GUI;

import javax.swing.JFrame;

/**
 *
 * the GUI for welcome dialog
 * 
 * @author Yu Liu
 */
public class WelcomeDialog extends javax.swing.JDialog {

    public static final int RET_EXIT = 0;
   
    public static final int RET_OK = 1;
    /**
     * Creates new form WelcomeDialog
     * @param parent
     * @param modal  
     */
    public WelcomeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        WindowUtil.center(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonRegister = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(200, 300));
        setModal(true);
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));
        getContentPane().add(jPanel1);

        buttonRegister.setText("Register");
        buttonRegister.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(buttonRegister);

        getContentPane().add(jPanel2);

        buttonLogin.setText("Login");
        buttonLogin.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel3.add(buttonLogin);

        getContentPane().add(jPanel3);

        buttonExit.setText("Exit");
        buttonExit.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        jPanel4.add(buttonExit);

        getContentPane().add(jPanel4);
        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        returnStatus=RET_EXIT;
        setVisible(false);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        LoginDialog loginDialog=new LoginDialog((JFrame)getParent(), true);
        setVisible(false);
        loginDialog.setVisible(true);
        if(loginDialog.getReturnStatus()==LoginDialog.RET_OK){
            returnStatus=RET_OK;
        }else{
            setVisible(true);
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        RegisterDialog registerDialog=new RegisterDialog((JFrame)getParent(), true);
        setVisible(false);
        registerDialog.setVisible(true);        
        if(registerDialog.getReturnStatus()==RegisterDialog.RET_OK){
            returnStatus=RET_OK;
        }else{
            setVisible(true);
        }
    }//GEN-LAST:event_buttonRegisterActionPerformed



    /**
     * return to the welcome dialog status
     * @return
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_EXIT;
}
